name: replay_trajectory_paper
channels:
- defaults
- conda-forge
- edeno
dependencies:
- "python >= 3.6"
- numpy
- "pandas >= 0.21.0"
- scipy
- matplotlib
- seaborn
- tqdm
- xarray
- dask
- "loren_frank_data_processing == 0.9.15.dev0"
- "ripple_detection == 0.1.9.dev0"
- "replay_trajectory_classification == 0.7.7.dev0"
- jupyter
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
- pip
- pip:
  - UpSetPlot
  - nb-black
