name: replay_trajectory_paper
channels:
- defaults
- conda-forge
- edeno
dependencies:
- "python >= 3.6"
- numpy
- "pandas >= 0.21.0"
- scipy
- matplotlib
- seaborn
- tqdm
- xarray
- dask
- loren_frank_data_processing
- ripple_detection
- replay_trajectory_classification
- jupyter
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
